### GET all listings
GET http://localhost:8080/listing?includeOffers=false

### GET listing by id
GET http://localhost:8080/listing/b85a315a-124c-45d1-baa4-dcf9dc9e3745?includeOffers=true

### Create listing
POST http://localhost:8080/listing
Content-Type: application/json

{
  "address": "9050 AHHH st",
  "agentName": "Big Boss",
  "propertyType": "HOUSE",
  "listingPrice": 300000.0
}

### GET all offers of listing
GET http://localhost:8080/listing/08001001-99ec-4674-948d-15db186b6f46/offer

### GET single offer of listing
GET http://localhost:8080/listing/08001001-99ec-4674-948d-15db186b6f46/offer/5b2f570f-7a5d-46cf-a7e9-fe9133720a55

### PUT listing
PUT http://localhost:8080/listing/b85a315a-124c-45d1-baa4-dcf9dc9e3745
Content-Type: application/json

{
  "address": "9050 AHHH st",
  "agentName": "Big toss",
  "propertyType": "HOUSE",
  "listingPrice": 300000.0
}

### Create offer on a listing
POST http://localhost:8080/listing/b85a315a-124c-45d1-baa4-dcf9dc9e3745/offer
Content-Type: application/json

{
  "offerPrice": 666666.0,
  "lenderName": "Big Hotdogs",
  "status": "ACCEPTED"
}

### PUT offer on listing
PUT http://localhost:8080/listing/b85a315a-124c-45d1-baa4-dcf9dc9e3745/offer/045274f8-dd6b-4a38-8b57-7f81b746648a
Content-Type: application/json

{
  "offerPrice": 666666.0,
  "lenderName": "Big Hotdogs2",
  "status": "CANCELED"
}

### PATCH listing
PATCH http://localhost:8080/listing/5567a960-1d90-4451-8a41-98c87e1e89bc
Content-Type: application/json

{
  "listingPrice": 500000.0,
  "agentName": "Mr. Beast"
}

### PATCH offer
PATCH http://localhost:8080/listing/f4c52dad-014c-481d-853b-afd4566f4432/offer/ff02f0d0-1e7a-4ed7-92b8-89b27a69bb23
Content-Type: application/json

{
  "status": "PENDING"
}

### DELETE listing
DELETE http://localhost:8080/listing/a0b6fb25-1d63-4a43-b1d1-b842181d8d37