### GET all listings
GET http://localhost:8080/listing?includeOffers=true

### GET listing by id
GET http://localhost:8080/listing/3bec57b7-23bd-4b74-b4ba-1b9be53fa513?includeOffers=true

### Create listing
POST http://localhost:8080/listing
Content-Type: application/json

{
  "address": "9050 AHHH st",
  "agentName": "Big Boss",
  "propertyType": "HOUSE",
  "listingPrice": 300000.0,
  "offers": [
    {
      "offerPrice": 310000.0,
      "lenderName": "Super Big Finance",
      "status": "PENDING"
    },
    {
      "offerPrice": 290000.0,
      "lenderName": "MEh Finance",
      "status": "CANCELED"
    }
  ]
}

### GET all offers of listing
GET http://localhost:8080/listing/5efd2ef1-d5be-4ad3-8863-7b2d4588e0f7/offer

### GET single offer of listing
GET http://localhost:8080/listing/5efd2ef1-d5be-4ad3-8863-7b2d4588e0f7/offer/3941cb13-8bdd-4f9d-8305-2426d0895277

### PUT listing
PUT http://localhost:8080/listing/0a2cdb26-e672-49c8-8e72-35b16bac81be
Content-Type: application/json

{
  "address": "9050 AHHH st",
  "agentName": "Big Boss",
  "propertyType": "HOUSE",
  "listingPrice": 300000.0
}

### Create offer on a listing
POST http://localhost:8080/listing/23e01a5d-6a4b-45d8-ac3a-25a3e1d8db2b/offer
Content-Type: application/json

{
  "offerPrice": 666666.0,
  "lenderName": "Big Hotdogs",
  "status": "ACCEPTED"
}

### PUT offer on listing
PUT http://localhost:8080/listing/23e01a5d-6a4b-45d8-ac3a-25a3e1d8db2b/offer/045274f8-dd6b-4a38-8b57-7f81b746648a
Content-Type: application/json

{
  "offerPrice": 666666.0,
  "lenderName": "Big Hotdogs2",
  "status": "CANCELED"
}

### PATCH listing
PATCH http://localhost:8080/listing/5567a960-1d90-4451-8a41-98c87e1e89bc
Content-Type: application/json

{
  "listingPrice": 500000.0,
  "agentName": "Mr. Beast"
}

### PATCH offer
PATCH http://localhost:8080/listing/f4c52dad-014c-481d-853b-afd4566f4432/offer/ff02f0d0-1e7a-4ed7-92b8-89b27a69bb23
Content-Type: application/json

{
  "status": "PENDING"
}

### DELETE listing
DELETE http://localhost:8080/listing/a0b6fb25-1d63-4a43-b1d1-b842181d8d37